# Generated by Django 2.0.4 on 2018-04-27 07:07

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20180427_1228'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='likes',
            field=models.ManyToManyField(blank=True, default='0', related_name='likes', to=settings.AUTH_USER_MODEL),
        ),
    ]
